# Generated by Django 6.0.5 on 2026-05-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_course_department_group_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_headman",
        ),
    ]
