# Generated by Django 6.0.5 on 2026-05-24 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_is_headman"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(unique=True)),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
            ],
            options={
                "verbose_name": "Часовий слот (Пара)",
                "verbose_name_plural": "Часові слоти (Пари)",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building", models.CharField(max_length=50)),
                (
                    "number",
                    models.CharField(help_text="Номер аудиторії", max_length=20),
                ),
                ("type", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Аудиторія",
                "verbose_name_plural": "Аудиторії",
                "unique_together": {("building", "number")},
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="Номер семестру (1 або 2)"
                    ),
                ),
                ("year", models.CharField(max_length=9)),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Семестр",
                "verbose_name_plural": "Семестри",
                "unique_together": {("year", "number")},
            },
        ),
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="users.course",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_offerings",
                        to="users.group",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "TEACHER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_offerings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_offerings",
                        to="users.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проведення курсу",
                "verbose_name_plural": "Проведення курсів",
                "unique_together": {("course", "teacher", "semester", "group")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(max_length=20, verbose_name="Day of week"),
                ),
                (
                    "course_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_entries",
                        to="users.courseoffering",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_entries",
                        to="users.room",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_entries",
                        to="users.timeslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запис розкладу",
                "verbose_name_plural": "Записи розкладу",
            },
        ),
    ]
