# Generated by Django 6.0.5 on 2026-06-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_timeslot_room_semester_courseoffering_scheduleentry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseoffering",
            options={
                "verbose_name": "Course Offering",
                "verbose_name_plural": "Course Offerings",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Room", "verbose_name_plural": "Rooms"},
        ),
        migrations.AlterModelOptions(
            name="scheduleentry",
            options={
                "verbose_name": "Schedule Entry",
                "verbose_name_plural": "Schedule Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="semester",
            options={"verbose_name": "Semester", "verbose_name_plural": "Semesters"},
        ),
        migrations.AlterModelOptions(
            name="timeslot",
            options={
                "ordering": ["number"],
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
            },
        ),
    ]
