# Generated by Django 6.0.5 on 2026-06-19 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_lesson_abtest_grade_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseoffering",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="telegram_group_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_year", models.PositiveIntegerField(blank=True, null=True)),
                ("faculty", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "degree_level",
                    models.CharField(
                        blank=True,
                        help_text="Бакалавр/Магістр",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("office_room", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "telegram_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
