# Generated by Django 6.0.5 on 2026-06-24 16:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_courseoffering_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="users.lesson",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="score",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
