# Generated by Django 6.0.5 on 2026-07-05 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_attendance_lesson_alter_grade_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("it", "Italiano"),
                    ("de", "Deutsch"),
                    ("es", "Espanol"),
                    ("uk", "Ukrainian"),
                ],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("LATE", "Late"),
                ],
                default="PRESENT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("ADMIN", "Admin"),
                    ("TEACHER", "Teacher"),
                ],
                default="STUDENT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="topic",
            field=models.CharField(
                blank=True, help_text="Lesson topic", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.CharField(help_text="Room number", max_length=20),
        ),
        migrations.AlterField(
            model_name="semester",
            name="number",
            field=models.PositiveSmallIntegerField(
                help_text="Semester number (1 or 2)"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="degree_level",
            field=models.CharField(
                blank=True, help_text="Bachelor/Master", max_length=50, null=True
            ),
        ),
    ]
