# Generated by Django 6.0.5 on 2026-07-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_customuser_language_alter_attendance_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseoffering",
            name="assessment_rules",
            field=models.CharField(
                default="60% coursework / 40% exam",
                help_text="Grading breakdown",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="attendance_required_percentage",
            field=models.PositiveSmallIntegerField(
                default=75, help_text="Required attendance percentage"
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="ects_credits",
            field=models.PositiveSmallIntegerField(
                default=5, help_text="ECTS credits count"
            ),
        ),
        migrations.AlterField(
            model_name="courseoffering",
            name="description",
            field=models.TextField(
                blank=True, help_text="Course syllabus and description", null=True
            ),
        ),
    ]
